pragma ComponentBehavior: Bound
import "../.."
import QtQuick
import Quickshell
import Quickshell.Io

// Tiling layouts — switch the active layout and build custom ones on top of the hypr.lua
// layout API (hl.layout.register). A custom layout is a parametric template (columns / rows /
// grid / main+stack); this page generates $VELUMERON_USER_DIR/hypr.lua/user_layouts.lua from
// the specs in settings.json (custom_layouts) and reloads Hyprland. The generated file also
// restores the persisted layout choice (tiling_layout) on every reload — a runtime hl.config
// would otherwise reset to the config default whenever e.g. a wallpaper change reloads.
Item {
    id: root

    function save(key, value) { SettingsStore.set(key, value) }

    readonly property var kinds: [
        { key: "columns",    label: "Columns",      icon: "󰕭", hint: "one equal column per window" },
        { key: "rows",       label: "Rows",         icon: "󰕳", hint: "one row per window (vertical stack)" },
        { key: "grid",       label: "Grid",         icon: "󰕰", hint: "auto-balanced grid" },
        { key: "main_stack", label: "Main + stack", icon: "󰨑", hint: "big main window, the rest stacked beside it" }
    ]
    function kindMeta(k) {
        for (var i = 0; i < kinds.length; i++) if (kinds[i].key === k) return kinds[i]
        return kinds[0]
    }

    // ── Lua generation ────────────────────────────────────────────────────────
    function luaBody(l) {
        if (l.kind === "columns")
            return "    for i, t in ipairs(ctx.targets) do t:place(ctx:column(i, n)) end"
        if (l.kind === "rows")
            return "    for i, t in ipairs(ctx.targets) do t:place(ctx:row(i, n)) end"
        if (l.kind === "grid")
            return "    for i, t in ipairs(ctx.targets) do t:place(ctx:grid_cell(i, n)) end"
        // main_stack — manual fraction rects (rects are monitor px incl. gaps_out/reserved).
        var ratio = ((l.ratio ?? 60) / 100).toFixed(2)
        var g     = l.gap ?? 8
        var right = l.side === "right"
        return [
            "    local full = ctx:row(1, 1)",
            "    if n == 1 then ctx.targets[1]:place(full) return end",
            "    local g = " + g,
            "    local mw = math.floor(full.w * " + ratio + ") - math.floor(g / 2)",
            "    local mx = " + (right ? "full.x + full.w - mw" : "full.x"),
            "    local sx = " + (right ? "full.x" : "full.x + mw + g"),
            "    local sw = full.w - mw - g",
            "    local sh = (full.h - g * (n - 2)) / (n - 1)",
            "    ctx.targets[1]:place({ x = mx, y = full.y, w = mw, h = full.h })",
            "    for i = 2, n do",
            "        ctx.targets[i]:place({ x = sx, y = full.y + (i - 2) * (sh + g), w = sw, h = sh })",
            "    end"
        ].join("\n")
    }
    function luaFile(layouts) {
        var out = [
            "-- Generated by Velumeron (Settings → Layouts) — do not edit; rewritten on every change.",
            "-- Custom tiling layouts, usable as general.layout = \"lua:<name>\" (and in workspace rules).",
            "local function reg(name, fn)",
            "    local ok, err = pcall(hl.layout.register, name, { recalculate = fn })",
            "    if not ok then print(\"user_layouts: \" .. tostring(err)) end",
            "end",
            ""
        ]
        for (var i = 0; i < layouts.length; i++) {
            out.push("reg(\"" + layouts[i].name + "\", function(ctx)")
            out.push("    local n = #ctx.targets")
            out.push("    if n == 0 then return end")
            out.push(root.luaBody(layouts[i]))
            out.push("end)")
            out.push("")
        }
        out.push("-- Restore the persisted layout choice — a runtime hl.config() doesn't survive reloads.")
        out.push("do")
        out.push("    local f = io.popen(\"jq -r '.tiling_layout // \\\"\\\"' '\" .. VTL_USER_DIR .. \"/gui/settings.json' 2>/dev/null\")")
        out.push("    if f then")
        out.push("        local v = f:read(\"l\") or \"\"")
        out.push("        f:close()")
        out.push("        if v ~= \"\" then pcall(hl.config, { general = { layout = v } }) end")
        out.push("    end")
        out.push("end")
        return out.join("\n") + "\n"
    }
    // Persist the spec list, regenerate user_layouts.lua, reload Hyprland.
    Process { id: genProc; onExited: reloadProc.running = true }
    Process { id: reloadProc; command: ["hyprctl", "reload"] }
    function applyLayouts(layouts) {
        root.save("custom_layouts", layouts)
        genProc.command = ["python3", "-c",
            "import sys,os; p=sys.argv[1]; os.makedirs(os.path.dirname(p),exist_ok=True); open(p,'w').write(sys.argv[2])",
            (Quickshell.env("VELUMERON_USER_DIR")
             || (Quickshell.env("XDG_CONFIG_HOME") || Quickshell.env("HOME") + "/.config") + "/velumeron")
            + "/hypr.lua/user_layouts.lua",
            root.luaFile(layouts)]
        genProc.running = false; genProc.running = true
    }

    // ── Switch the active layout (persist + apply live) ───────────────────────
    // Applied through VTL_layouts_apply() rather than a direct hl.config: "float" is a policy,
    // not a compositor layout, and hl.config would happily set general:layout to a name that
    // doesn't exist. layout_manager.lua maps the policy modes onto a real layout.
    Process { id: switchProc; onExited: UiState.layoutPollSerial++ }
    function setLayout(value) {
        root.save("tiling_layout", value)
        // Value passed straight to Lua: root.save is async, so re-reading the file there raced the
        // write and applied the previous choice (see layout_manager.lua).
        switchProc.command = ["bash", "-c", "hyprctl eval \"VTL_layouts_set([[$1]])\"", "vtl", value]
        switchProc.running = false; switchProc.running = true
    }
    readonly property var allLayouts: {
        var out = [{ value: "dwindle", label: "Dwindle" }, { value: "master", label: "Master" },
                   { value: "monocle", label: "Monocle" }, { value: "float",  label: "Float" }]
        var cs = VtlConfig.customLayouts
        for (var i = 0; i < cs.length; i++)
            out.push({ value: "lua:" + cs[i].name, label: cs[i].name + "  (custom)" })
        return out
    }

    // ── Per-monitor / per-workspace assignments ───────────────────────────────
    // Overrides live in layout_monitors / layout_workspaces (precedence: workspace > monitor >
    // global); after every write layout_manager.lua re-applies them live via VTL_layouts_apply().
    Process { id: assignProc; onExited: UiState.layoutPollSerial++ }
    // Scope + value go to Lua directly — root.save is async and re-reading the file in Lua raced
    // the write (see layout_manager.lua). An empty mode clears the override.
    function applyMonitor(name, mode) {
        assignProc.command = ["bash", "-c",
            "hyprctl eval \"VTL_layouts_set_monitor([[$1]], [[$2]])\"", "vtl", name, mode]
        assignProc.running = false; assignProc.running = true
    }
    function applyWorkspace(id, mode) {
        assignProc.command = ["bash", "-c",
            "hyprctl eval \"VTL_layouts_set_workspace([[$1]], [[$2]])\"", "vtl", "" + id, mode]
        assignProc.running = false; assignProc.running = true
    }
    // Dropdown options for an assignment: "" = follow the global layout. Endless (a scrolling
    // strip of max-2-window workspaces) only exists per monitor, not per workspace.
    function assignOptions(cur, withEndless) {
        var out = [{ label: "Auto (follow global)", key: "", on: cur === "" }]
        var modes = root.allLayouts.slice(0, 4)
        if (withEndless) modes.push({ value: "endless", label: "Endless (strip)" })
        var cs = VtlConfig.customLayouts
        for (var i = 0; i < cs.length; i++)
            modes.push({ value: "lua:" + cs[i].name, label: cs[i].name + "  (custom)" })
        for (var j = 0; j < modes.length; j++)
            out.push({ label: modes[j].label, key: modes[j].value, on: cur === modes[j].value })
        return out
    }
    function assignLabel(v) {
        if (v === "") return "Auto (follow global)"
        if (v === "endless") return "Endless (strip)"
        for (var i = 0; i < root.allLayouts.length; i++)
            if (root.allLayouts[i].value === v) return root.allLayouts[i].label
        return v
    }
    function setMonitorMode(name, mode) {
        var m = {}
        var cur = VtlConfig.layoutMonitors
        for (var k in cur) m[k] = cur[k]
        if (mode === "") delete m[name]; else m[name] = mode
        root.save("layout_monitors", m)
        root.applyMonitor(name, mode)
    }
    function setWorkspaceMode(id, mode) {
        var m = {}
        var cur = VtlConfig.layoutWorkspaces
        for (var k in cur) m[k] = cur[k]
        if (mode === "") delete m["" + id]; else m["" + id] = mode
        root.save("layout_workspaces", m)
        root.applyWorkspace(id, mode)
    }

    Flickable {
        anchors.fill: parent
        contentHeight: col.implicitHeight
        clip: true
        boundsBehavior: Flickable.StopAtBounds

        Column {
            id: col
            width: parent.width
            topPadding: 4
            spacing: Style.cardGap

            Card {
                CardLabel { text: "ACTIVE LAYOUT"
                            hint: "Also switchable from the bar's Layout module. The choice survives reloads." }
                Dropdown {
                    summary: {
                        var v = VtlConfig.tilingLayout
                        for (var i = 0; i < root.allLayouts.length; i++)
                            if (root.allLayouts[i].value === v) return root.allLayouts[i].label
                        return v
                    }
                    options: root.allLayouts.map(function (l) {
                        return { label: l.label, key: l.value, on: VtlConfig.tilingLayout === l.value }
                    })
                    onPicked: key => root.setLayout(key)
                }
            }

            Card {
                CardLabel { text: "ASSIGNMENTS"
                            hint: "Pin a layout to a monitor or a workspace — workspace beats monitor beats " +
                                  "global. “Endless (strip)” is monitor-only: it turns the monitor into a " +
                                  "scrolling band of max-2-window workspaces." }

                // Per-monitor override: one dropdown per connected screen.
                FieldLabel { text: "Per monitor" }
                Repeater {
                    model: Quickshell.screens
                    delegate: Column {
                        id: mrow
                        required property var modelData
                        readonly property string cur: VtlConfig.layoutMonitors[mrow.modelData.name] ?? ""
                        width: parent.width; spacing: 4
                        Text {
                            text:  mrow.modelData.name
                            color: Colors.fgPrimary; font.pixelSize: Style.fsLabel; font.family: Style.font
                        }
                        Dropdown {
                            summary: root.assignLabel(mrow.cur)
                            options: root.assignOptions(mrow.cur, true)
                            onPicked: key => root.setMonitorMode(mrow.modelData.name, key)
                        }
                    }
                }

                // Per-workspace overrides: the existing ones as rows, plus an add-control.
                FieldLabel { text: "Per workspace"
                             hint: "Also switchable on the fly with Super+Alt+Tab." }
                Repeater {
                    model: Object.keys(VtlConfig.layoutWorkspaces)
                               .sort(function (a, b) { return Number(a) - Number(b) })
                    delegate: Rectangle {
                        id: wrow
                        required property var modelData
                        width: parent.width; height: 40
                        radius: Style.rControl
                        color:  Style.controlFill
                        border.width: Style.controlBorderW
                        border.color: Style.controlBorderColor

                        Text {
                            anchors { left: parent.left; leftMargin: 12; verticalCenter: parent.verticalCenter }
                            text:  "Workspace " + wrow.modelData
                            color: Colors.fgPrimary; font.pixelSize: Style.fsLabel; font.family: Style.font
                        }
                        Text {
                            anchors { left: parent.left; leftMargin: 130; right: wrmB.left; rightMargin: 8
                                      verticalCenter: parent.verticalCenter }
                            elide: Text.ElideRight
                            text:  root.assignLabel(VtlConfig.layoutWorkspaces[wrow.modelData] ?? "")
                            color: Colors.fgMuted; font.pixelSize: Style.fsSub; font.family: Style.font
                        }
                        TextButton {
                            id: wrmB
                            anchors { right: parent.right; rightMargin: 8; verticalCenter: parent.verticalCenter }
                            label: "Remove"
                            onClicked: root.setWorkspaceMode(wrow.modelData, "")
                        }
                    }
                }
                Stepper {
                    id: wsIdStep
                    label: "Workspace"
                    value: 1; step: 1; min: 1; max: 20
                    onChanged: v => wsIdStep.value = v
                }
                Dropdown {
                    id: wsModePick
                    property string mode: "dwindle"
                    summary: root.assignLabel(wsModePick.mode)
                    options: root.assignOptions(wsModePick.mode, false)
                    onPicked: key => wsModePick.mode = key
                }
                Row {
                    spacing: 8
                    TextButton {
                        label: "Add override"
                        primary: true
                        onClicked: root.setWorkspaceMode(wsIdStep.value, wsModePick.mode)
                    }
                }
            }

            Card {
                CardLabel { text: "CUSTOM LAYOUTS"
                            hint: "Built on the Lua layout API — pick a template, tune it, done. Custom layouts " +
                                  "appear in the bar module and can be used in workspace rules as “lua:<name>”."
                                  + "\n\n" + "Adding one saves it, regenerates user_layouts.lua and reloads Hyprland." }

                // Existing custom layouts.
                Repeater {
                    model: VtlConfig.customLayouts
                    delegate: Rectangle {
                        id: lrow
                        required property var modelData
                        width: parent.width; height: 40
                        radius: Style.rControl
                        color:  Style.controlFill
                        border.width: Style.controlBorderW
                        border.color: Style.controlBorderColor

                        Text {
                            anchors { left: parent.left; leftMargin: 12; verticalCenter: parent.verticalCenter }
                            text:  root.kindMeta(lrow.modelData.kind).icon
                            color: Style.accent; font.pixelSize: 15; font.family: Style.font
                        }
                        Column {
                            anchors { left: parent.left; leftMargin: 38; right: rmB.left; rightMargin: 8
                                      verticalCenter: parent.verticalCenter }
                            spacing: 1
                            Text {
                                width: parent.width; elide: Text.ElideRight
                                text:  lrow.modelData.name
                                color: Colors.fgPrimary; font.pixelSize: Style.fsLabel; font.family: Style.font
                            }
                            Text {
                                width: parent.width; elide: Text.ElideRight
                                text:  root.kindMeta(lrow.modelData.kind).label
                                       + (lrow.modelData.kind === "main_stack"
                                          ? "  ·  " + (lrow.modelData.ratio ?? 60) + "% "
                                            + (lrow.modelData.side === "right" ? "right" : "left") : "")
                                       + "  ·  gap " + (lrow.modelData.gap ?? 8)
                                color: Colors.fgMuted; font.pixelSize: Style.fsSub; font.family: Style.font
                            }
                        }
                        TextButton {
                            id: rmB
                            anchors { right: parent.right; rightMargin: 8; verticalCenter: parent.verticalCenter }
                            label: "Remove"
                            onClicked: {
                                var keep = VtlConfig.customLayouts.filter(function (l) {
                                    return l.name !== lrow.modelData.name
                                })
                                root.applyLayouts(keep)
                            }
                        }
                    }
                }

                // Builder.
                FieldLabel { text: "New layout" }
                Rectangle {
                    id: nameField
                    property alias text: nameInput.text
                    width: parent.width; height: 34
                    radius: Style.rControl; color: Style.controlFill
                    border.width: nameInput.activeFocus ? 1 : Style.controlBorderW
                    border.color: nameInput.activeFocus ? Style.accent : Style.controlBorderColor
                    TextInput {
                        id: nameInput
                        anchors.fill: parent; anchors.leftMargin: 12; anchors.rightMargin: 12
                        verticalAlignment: TextInput.AlignVCenter
                        color: Colors.fgBright; font.pixelSize: 12; font.family: Style.font
                        clip: true; selectByMouse: true
                    }
                    Text {
                        anchors { left: parent.left; leftMargin: 12; verticalCenter: parent.verticalCenter }
                        visible: nameInput.text === "" && !nameInput.activeFocus
                        text: "Name (e.g. coding)"
                        color: Colors.fgMuted; font.pixelSize: 11; font.family: Style.font
                    }
                }
                FieldLabel { text: "Template" }
                Segmented {
                    id: kindPick
                    equal: true
                    property string kind: "main_stack"
                    current: kind
                    segments: root.kinds.map(function (k) { return { label: k.label, key: k.key } })
                    onPicked: key => kindPick.kind = key
                }
                // Stays visible: it describes the template you just picked, and changes with it.
                SubLabel { width: parent.width; text: root.kindMeta(kindPick.kind).hint }
                Stepper {
                    id: ratioStep
                    visible: kindPick.kind === "main_stack"
                    label: "Main size"; unit: "%"
                    value: 60; step: 5; min: 30; max: 80
                    onChanged: v => ratioStep.value = v
                }
                Segmented {
                    id: sidePick
                    visible: kindPick.kind === "main_stack"
                    property string side: "left"
                    current: side
                    segments: [{ label: "Main left", key: "left" }, { label: "Main right", key: "right" }]
                    onPicked: key => sidePick.side = key
                }
                Stepper {
                    id: gapStep
                    label: "Gap"; unit: "px"
                    value: 8; step: 2; min: 0; max: 32
                    onChanged: v => gapStep.value = v
                }
                Row {
                    spacing: 8
                    TextButton {
                        label: "Add layout"
                        primary: true
                        onClicked: {
                            var name = nameField.text.trim().toLowerCase().replace(/[^a-z0-9-]/g, "")
                            if (name === "" || name === "dwindle" || name === "master") return
                            var next = VtlConfig.customLayouts.filter(function (l) { return l.name !== name })
                            next = next.concat([{
                                name: name, kind: kindPick.kind, gap: gapStep.value,
                                ratio: ratioStep.value, side: sidePick.side
                            }])
                            root.applyLayouts(next)
                            nameField.text = ""
                        }
                    }
                }
            }
        }
    }
}
