foreground         #FFD4C3
background         #080301
background_opacity 1.0
cursor             #8EB0AC
active_tab_foreground     #080301
active_tab_background     #FFD4C3
inactive_tab_foreground   #FFD4C3
inactive_tab_background   #080301
active_border_color   #FFD4C3
inactive_border_color #080301
bell_border_color     #2C214E
color0       #0C0402
color8       #A88273
color1       #2C214E
color9       #2C214E
color2       #823658
color10      #823658
color3       #A7412B
color11      #A7412B
color4       #206B8C
color12      #206B8C
color5       #0E8B95
color13      #0E8B95
color6       #D66F48
color14      #D66F48
color7       #F7CAB9
color15      #F2DCD4
