foreground         #FF6147
background         #080302
background_opacity 1.0
cursor             #CA452D
active_tab_foreground     #080302
active_tab_background     #FF6147
inactive_tab_foreground   #FF6147
inactive_tab_background   #080302
active_border_color   #FF6147
inactive_border_color #080302
bell_border_color     #67573B
color0       #0B0403
color8       #EB0000
color1       #67573B
color9       #67573B
color2       #632927
color10      #632927
color3       #7D7447
color11      #7D7447
color4       #378368
color12      #378368
color5       #AD442F
color13      #AD442F
color6       #3FAE6D
color14      #3FAE6D
color7       #FF513A
color15      #F7A094
