foreground         #FFE057
background         #030308
background_opacity 1.0
cursor             #A2D3A1
active_tab_foreground     #030308
active_tab_background     #FFE057
inactive_tab_foreground   #FFE057
inactive_tab_background   #030308
active_border_color   #FFE057
inactive_border_color #030308
bell_border_color     #91534B
color0       #06050C
color8       #BD8B00
color1       #91534B
color9       #91534B
color2       #4B5792
color10      #4B5792
color3       #15888E
color11      #15888E
color4       #CC574B
color12      #CC574B
color5       #2EC1EB
color13      #2EC1EB
color6       #FFBF28
color14      #FFBF28
color7       #FFDA50
color15      #F7E49F
