#size	xhot	yhot	Path to PNG image	delay
24	1	1	/tmp/tmp.hRc17jloiP/default_000.png	50
32	1	1	/tmp/tmp.hRc17jloiP/default_001.png	50
48	2	2	/tmp/tmp.hRc17jloiP/default_002.png	50
64	2	2	/tmp/tmp.hRc17jloiP/default_003.png	50
