#size	xhot	yhot	Path to PNG image	delay
24	4	4	/tmp/tmp.S9tppTngRw/left_ptr_000.png	50
30	5	5	/tmp/tmp.S9tppTngRw/left_ptr_001.png	50
36	6	6	/tmp/tmp.S9tppTngRw/left_ptr_002.png	50
48	8	8	/tmp/tmp.S9tppTngRw/left_ptr_003.png	50
