set fish_color_autosuggestion {color8}
set fish_color_cancel {color1} '--reverse'
set fish_color_command {color6}
set fish_color_comment {color8}
set fish_color_cwd {color5}
set fish_color_cwd_root {color1}
set fish_color_end {color4}
set fish_color_error {color1}
set fish_color_escape {color3}
set fish_color_history_current --bold
set fish_color_host {color7}
set fish_color_host_remote {color7}
set fish_color_keyword {color3}
set fish_color_match --background={color14}
set fish_color_normal {foreground}
set fish_color_operator {color11}
set fish_color_option {color4}
set fish_color_param {color7}
set fish_color_quote {color5}
set fish_color_redirection {color3}
set fish_color_search_match --background={color8}
set fish_color_selection --background={color8}
set fish_color_status {color1}
set fish_color_user {color6}
set fish_color_valid_path --underline
set fish_pager_color_background {background}
set fish_pager_color_completion {foreground}
set fish_pager_color_description {color8}
set fish_pager_color_prefix {color6}
set fish_pager_color_progress {color8}
set fish_pager_color_secondary_background {background}
set fish_pager_color_secondary_completion {foreground}
set fish_pager_color_secondary_description {color8}
set fish_pager_color_secondary_prefix {color6}
set fish_pager_color_selected_background --background={color8}
set fish_pager_color_selected_completion {foreground}
set fish_pager_color_selected_description {color8}
set fish_pager_color_selected_prefix {color6}
