#!/usr/bin/env bash
# Global window decoration — Settings → Window rules → "Global window look".
#
# Persists the four knobs as lnf_* vars in a generated hypr.lua include (read by
# look_and_feel + windowrules at config load) AND pushes them to the running compositor
# live, so a change is visible immediately and survives a Hyprland reload/restart.
#
#   apply-decoration.sh <opacity 0..1> <blur 0|1> <vibrancy 0..1> <xray 0|1>
#
# NOTE on portability: opacity is the global window transparency (broadly a compositor
# concept); blur / vibrancy / x-ray are Hyprland decoration features — sway/niri have no
# blur at all. Off Hyprland the hyprctl calls below are simply skipped (no-op), and the
# generated lnf_* vars only matter to the hypr.lua config. This script is the seam a
# future Compositor backend would reimplement per window manager.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")" && pwd)"
source "$SCRIPT_DIR/lib/env.sh"

O="${1:-0.92}"; B="${2:-1}"; V="${3:-0.2}"; X="${4:-1}"
[[ "$B" == 1 ]] && b_lua=true || b_lua=false
[[ "$X" == 1 ]] && x_lua=true || x_lua=false

# ── Persist: the include hyprland.lua dofiles before look_and_feel/windowrules read it ──
DEC="$VELUMERON_USER_DIR/hypr.lua/user_decoration.lua"
mkdir -p "$(dirname "$DEC")"
cat > "$DEC" <<EOF
-- Generated by apply-decoration.sh (Settings → Window rules → Global window look). Do not edit.
lnf_window_opacity = $O
lnf_blur_enabled   = $b_lua
lnf_vibrancy       = $V
lnf_xray           = $x_lua
EOF

# ── Live apply to the running compositor (skipped off Hyprland) ──
if command -v hyprctl >/dev/null 2>&1 && hyprctl version >/dev/null 2>&1; then
    hyprctl eval "hl.config({ decoration = { blur = { enabled = $b_lua, vibrancy = $V, xray = $x_lua } } })" >/dev/null 2>&1 || true
    hyprctl eval "hl.window_rule({ name = 'all', match = { class = '(.*)' }, opacity = $O })" >/dev/null 2>&1 || true
fi
