#!/usr/bin/env bash
# btop-drop.sh [monitor] [anchor_px] [edge] | close
# Toggle a themed btop dropdown — a kitty window that drops out of the bar like the calendar
# flyout. Right-click the bar's Performance module (passes its monitor + along-edge anchor +
# bar edge), or `qs ipc call btop toggle` / a keybind (no args → focused monitor, top centre).
#
# The window is a normal float (pinned, slide animation, positioned flush under the bar's
# reserved strip), so it works where a layer surface can't: quickshell has no terminal widget,
# but kitty + Hyprland rules get the same drop-out-of-the-bar feel. btop runs with
# XDG_CONFIG_HOME pointed at the velumeron user dir, so it uses OUR btop.conf + a theme
# generated live from the current wallust palette (colors.json) — accent colours included,
# and the user's own ~/.config/btop stays untouched.
source "$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")" && pwd)/lib/env.sh"

CLASS="velumeron-btop"
GAP=8

# ── Toggle off: if the dropdown exists, close it (also the explicit `close` verb) ────────────
# NOTE: this Hyprland runs the hypr.lua config runtime — `hyprctl dispatch` takes Lua
# (hl.dsp.*), `hyprctl keyword` is unavailable ("use eval"), so rules go via hl.window_rule.
pid=$(hyprctl clients -j 2>/dev/null | jq -r --arg c "$CLASS" '[.[] | select(.class==$c)][0].pid // ""')
if [[ -n "$pid" ]]; then
    kill "$pid" 2>/dev/null
    exit 0
fi
[[ "${1:-}" == "close" ]] && exit 0

command -v btop  >/dev/null || { notify-send "btop dropdown" "btop is not installed"; exit 1; }
command -v kitty >/dev/null || { notify-send "btop dropdown" "kitty is not installed"; exit 1; }

MON="${1:-}"; ANCHOR="${2:-}"; EDGE="${3:-top}"

# ── Monitor geometry (logical: divide by scale, swap on 90°/270° transforms) ────────────────
mons=$(hyprctl monitors -j)
[[ -z "$MON" ]] && MON=$(jq -r '[.[] | select(.focused)][0].name // .[0].name' <<< "$mons")
read -r MX MY LW LH R_L R_T R_R R_B < <(jq -r --arg m "$MON" '
    [.[] | select(.name==$m)][0] |
    ((.transform % 2) == 1) as $rot |
    [ .x, .y,
      (if $rot then (.height/.scale) else (.width/.scale)  end),
      (if $rot then (.width/.scale)  else (.height/.scale) end),
      .reserved[0], .reserved[1], .reserved[2], .reserved[3] ] | @tsv' <<< "$mons")
[[ -z "$MX" || "$MX" == "null" ]] && exit 1

# ── Size from the Performance module's gear settings (percent of the monitor) ───────────────
gs="$VELUMERON_USER_DIR/gui/settings.json"
W_PCT=$(jq -r '.module_settings.performance.btop_width_pct  // 44' "$gs" 2>/dev/null || echo 44)
H_PCT=$(jq -r '.module_settings.performance.btop_height_pct // 55' "$gs" 2>/dev/null || echo 55)
W=$(awk -v w="$LW" -v p="$W_PCT" 'BEGIN{printf "%d", w*p/100}')
H=$(awk -v h="$LH" -v p="$H_PCT" 'BEGIN{printf "%d", h*p/100}')

# ── Position: flush against the bar's reserved strip on `edge`, centred on the anchor ───────
inner_x0=$(awk -v a="$MX" -v b="$R_L" 'BEGIN{printf "%d", a+b}')
inner_y0=$(awk -v a="$MY" -v b="$R_T" 'BEGIN{printf "%d", a+b}')
inner_x1=$(awk -v a="$MX" -v w="$LW" -v b="$R_R" 'BEGIN{printf "%d", a+w-b}')
inner_y1=$(awk -v a="$MY" -v h="$LH" -v b="$R_B" 'BEGIN{printf "%d", a+h-b}')

clamp() { awk -v v="$1" -v lo="$2" -v hi="$3" 'BEGIN{printf "%d", (v<lo?lo:(v>hi?hi:v))}'; }

case "$EDGE" in
    bottom) Y=$((inner_y1 - GAP - H)) ;;
    left|right|top) Y=$((inner_y0 + GAP)) ;;
esac
case "$EDGE" in
    left)   X=$((inner_x0 + GAP)) ;;
    right)  X=$((inner_x1 - GAP - W)) ;;
    *)      # top/bottom: centre on the module's along-edge anchor (monitor centre without one)
        [[ -z "$ANCHOR" ]] && ANCHOR=$(awk -v w="$LW" 'BEGIN{printf "%d", w/2}')
        X=$(clamp $((MX + ANCHOR - W / 2)) $((inner_x0 + GAP)) $((inner_x1 - GAP - W))) ;;
esac
if [[ "$EDGE" == "left" || "$EDGE" == "right" ]]; then
    [[ -z "$ANCHOR" ]] && ANCHOR=$(awk -v h="$LH" 'BEGIN{printf "%d", h/2}')
    Y=$(clamp $((MY + ANCHOR - H / 2)) $((inner_y0 + GAP)) $((inner_y1 - GAP - H)))
fi

# ── btop theme from the live palette (colors.json is wallust's quickshell output) ───────────
cj="$VELUMERON_USER_DIR/quickshell/colors.json"
if [[ -f "$cj" ]]; then
    eval "$(jq -r 'to_entries[] | "\(.key)=\"\(.value)\""' "$cj")"
else
    background="#020300"; foreground="#F6CF8D"
    color1="#4F5441"; color2="#795443"; color3="#427782"; color4="#A55D38"
    color5="#4D9387"; color6="#BE944B"; color7="#E8C281"; color8="#9F7E44"; color15="#EBD8B8"
fi

theme_dir="$VELUMERON_USER_DIR/btop/themes"
mkdir -p "$theme_dir"
cat > "$theme_dir/velumeron.theme" <<EOF
# Generated by btop-drop.sh from the live wallust palette — do not edit (rewritten each open).
theme[main_bg]=""
theme[main_fg]="$foreground"
theme[title]="$color15"
theme[hi_fg]="$color3"
theme[selected_bg]="$color3"
theme[selected_fg]="$color15"
theme[inactive_fg]="$color8"
theme[graph_text]="$color7"
theme[meter_bg]="$color1"
theme[proc_misc]="$color5"
theme[cpu_box]="$color5"
theme[mem_box]="$color5"
theme[net_box]="$color5"
theme[proc_box]="$color5"
theme[div_line]="$color1"
theme[temp_start]="$color5"
theme[temp_mid]="$color6"
theme[temp_end]="$color4"
theme[cpu_start]="$color3"
theme[cpu_mid]="$color6"
theme[cpu_end]="$color4"
theme[free_start]="$color2"
theme[free_mid]="$color3"
theme[free_end]="$color5"
theme[cached_start]="$color5"
theme[cached_mid]="$color3"
theme[cached_end]="$color6"
theme[available_start]="$color2"
theme[available_mid]="$color5"
theme[available_end]="$color3"
theme[used_start]="$color3"
theme[used_mid]="$color6"
theme[used_end]="$color4"
theme[download_start]="$color3"
theme[download_mid]="$color5"
theme[download_end]="$color6"
theme[upload_start]="$color2"
theme[upload_mid]="$color6"
theme[upload_end]="$color4"
theme[process_start]="$color3"
theme[process_mid]="$color6"
theme[process_end]="$color4"
EOF

# Our own btop.conf (XDG override makes btop read it). Create once — btop persists the user's
# in-app tweaks back into it, so only the theme line is enforced afterwards.
conf="$VELUMERON_USER_DIR/btop/btop.conf"
if [[ ! -f "$conf" ]]; then
    cat > "$conf" <<EOF
color_theme = "velumeron"
theme_background = False
truecolor = True
update_ms = 1500
rounded_corners = True
EOF
else
    sed -i 's/^color_theme.*/color_theme = "velumeron"/' "$conf"
fi

# ── Window rule (idempotent by name): float + slide + map at the right size ─────────────────
hyprctl eval "hl.window_rule({ name=\"btop_drop\", match={class=\"${CLASS}\"},
    float=true, size={\"${W}\",\"${H}\"}, animation=\"slide\" })" >/dev/null

# ── Spawn: velumeron kitty config (wallust colours + blur), btop on the velumeron profile ───
hyprctl dispatch "hl.dsp.exec_cmd([[kitty --class ${CLASS} --title sysmon-btop \
  -c '$VELUMERON_USER_DIR/kitty/kitty.conf' \
  -o remember_window_size=no -o window_padding_width=10 \
  /usr/bin/env XDG_CONFIG_HOME='$VELUMERON_USER_DIR' btop]])" >/dev/null

# Post-map: the main config's float_cap rule centres every float, so place it explicitly at
# the bar anchor once it exists, and pin it so it survives workspace switches.
for _ in $(seq 1 60); do
    pid=$(hyprctl clients -j | jq -r --arg c "$CLASS" '[.[] | select(.class==$c)][0].pid // ""')
    [[ -n "$pid" ]] && break
    sleep 0.05
done
if [[ -n "$pid" ]]; then
    hyprctl eval "for _,w in ipairs(hl.get_windows()) do
        if w.class == \"${CLASS}\" then
            hl.dispatch(hl.dsp.window.resize({ window=w, x=${W}, y=${H} }))
            hl.dispatch(hl.dsp.window.move({ window=w, x=${X}, y=${Y}, exact=true }))
            if not w.pinned then hl.dispatch(hl.dsp.window.pin({ window=w })) end
        end
    end" >/dev/null
fi
