// Generated by wallust — DO NOT edit manually.
// Template: vutureland/wallust/templates/colors.qml
pragma Singleton
import QtQuick

QtObject {
    readonly property color background: "#030404"
    readonly property color foreground: "#D38DFF"
    readonly property color color0:  "#050607"
    readonly property color color1:  "#423C72"
    readonly property color color2:  "#6D6089"
    readonly property color color3:  "#63339E"
    readonly property color color4:  "#795AAE"
    readonly property color color5:  "#888DBE"
    readonly property color color6:  "#8C44E6"
    readonly property color color7:  "#BD77FF"
    readonly property color color8:  "#8539E9"
    readonly property color color9:  "#423C72"
    readonly property color color10: "#6D6089"
    readonly property color color11: "#63339E"
    readonly property color color12: "#795AAE"
    readonly property color color13: "#888DBE"
    readonly property color color14: "#8C44E6"
    readonly property color color15: "#D6B2F7"

    // Semantic aliases — mirrors colors_gtk.css
    readonly property color bgPrimary:   color0
    readonly property color bgElement:   color1
    readonly property color bgSecondary: color2
    readonly property color bgActive:    color3
    readonly property color bgHover:     color4
    readonly property color boNormal:    color5
    readonly property color boActive:    color6
    readonly property color fgPrimary:   color7
    readonly property color fgMuted:     color8
    readonly property color fgUrgent:    color13
    readonly property color fgBright:    color15
}
