
#<< main monitor >>

background {
    monitor = {{mon1}}
    path = screenshot
    blur_passes = 4
    blur_size = 8
}
label {
    monitor = {{mon1}}
    text = cmd[update:1000] date +"%H:%M"
    font_size = 120
    font_family = Atomic Age
    color = rgb(255, 255, 255)
    halign = center
    valign = center
    position = 0, 0
}
input-field {
    monitor = {{mon1}}
    size = 300, 50
    outline_thickness = 2
    outer_color = rgba(255, 255, 255, 0.3)
    inner_color = rgba(0, 0, 0, 0.3)
    font_color = rgb(255, 255, 255)
    fade_on_empty = true
    placeholder_text = Password...
    halign = center
    valign = center
    position = 0, -200
}

#<< other monitors >>

background {
    monitor = {{mon2}}
    path = ~/.config/velumeron/assets/wallpaper/hyprlock/pure-black.jpg
}