# wallust v3.5
#
# You can copy this file to ~/.config/wallust/wallust.toml (keep in mind is a sample config)

# SIMPLE TUTORIAL, or `man wallust.5`:
# https://explosion-mental.codeberg.page/wallust/
#
# If comming from v2: https://explosion-mental.codeberg.page/wallust/v3.html#wallusttoml

# Global section - values below can be overwritten by command line flags

# How the image is parse, in order to get the colors:
# full - resized - wal - thumb -  fastresize - kmeans
backend = "wal"

# What color space to use to produce and select the most prominent colors:
# lab - labmixed - lch - lchmixed - salience
color_space = "lab"

# Use the most prominent colors in a way that makes sense, a scheme color palette:
# dark - dark16 - darkcomp - darkcomp16
# light - light16 - lightcomp - lightcomp16
# harddark - harddark16 - harddarkcomp - harddarkcomp16
# softdark - softdark16 - softdarkcomp - softdarkcomp16
# softlight - softlight16 - softlightcomp - softlightcomp16
# saliencedark - saliencedarkbalanced - saliencedarkdistributed - saliencedarklow (each has the 16 variations)
# salienceligh - saliencelightbalanced - saliencelightdistributed - saliencelightlow (each has the 16 variations)
palette = "saliencedarkdistributed"

# Ensures a "readable contrast" (OPTIONAL, disabled by default)
# Should only be enabled when you notice an unreadable contrast frequently happening
# with your images. The reference color for the contrast is the background color.
check_contrast = true

# Color saturation, between [1% and 100%] (OPTIONAL, disabled by default)
# usually something higher than 50 increases the saturation and below
# decreases it (on a scheme with strong and vivid colors)
saturation = 20

# Alpha value for templating, by default 100 (no other use whatsoever)
#alpha = 100



[templates]
# NOTE: prefer '' over "" for paths, avoids escaping.
# template: A RELATIVE path that points to `~/.config/wallust/template` (depends on platform)
# target: ABSOLUTE path in which to place a file with generated templated values.
# ¡ If either one is a directory, then both SHOULD be one. !
# zathura = { template = 'zathura', target = '~/.config/zathura/zathurarc' }

vscode       = { src = "vscode.json",            dst = "~/.cache/wallust/colors.json" }
vscode2      = { src = "vscode",                 dst = "~/.cache/wallust/colors" }
hyprland_lua = { src = "colors.lua",             dst = "~/.config/vutureland/hypr.lua/colors.lua"}
pywalfox     = { src = "pywal-colors",           dst = "~/.cache/wal/colors" }
pywalfox2    = { src = "pywal-colors.json",      dst = "~/.cache/wal/colors.json" }
fish         = { src = "colors.fish",            dst = "~/.cache/wallust/colors.fish"}
starship     = { src = "starship-palette.toml",  dst = "~/.cache/wallust/starship-palette.toml"}
   

kitty_config     = { src = "colors-kitty.conf",    dst = "~/.config/kitty/colors.conf"}
gtk3             = { src = "gtk3.css",             dst = "~/.config/gtk-3.0/wallust.css"}
gtk4             = { src = "colors_gtk4.css",      dst = "~/.config/gtk-4.0/wallust.css"}

kitty_vuture     = { src = "colors-kitty.conf",    dst = "~/.config/vutureland/kitty/colors.conf"}
rofi_vuture      = { src = "colors-rofi.conf",     dst = "~/.config/vutureland/rofi/assets/colors.rasi"}
colors_vuture    = { src = "colors_gtk.css",       dst = "~/.config/vutureland/assets/colors_gtk.css" }

[hooks]
hyprland_lua_colors = "~/.config/vutureland/assets/scripts/wallust/hyprland_lua-colors.sh && hyprctl reload"
pywalfox_update     = "pywalfox update"
swaync_update       = "killall -q swaync; ~/.config/vutureland/assets/scripts/launcher.sh --swaync"
waybar_update       = "sleep 0.8 && pkill -SIGUSR2 waybar"