general {
    lock_cmd                = pidof hyprlock || ~/.config/hypr/scripts/hyprlock.sh
    before_sleep_cmd        = 
    after_sleep_cmd         = 
}

listener {
    timeout                 = 420    
    on-timeout              = ~/.config/hypr/scripts/hyprlock.sh;
}

listener {
    timeout                 = 600    
}

listener {
    timeout                 = 1200      
    on-timeout              = systemctl suspend
}
