#################################################
#################################################
##     _         _            _             _
##    /_\  _   _| |_ ___  ___| |_ __ _ _ __| |_
##   //_\\| | | | __/ _ \/ __| __/ _` | '__| __|
##  /  _  \ |_| | || (_) \__ \ || (_| | |  | |_
##  \_/ \_/\__,_|\__\___/|___/\__\__,_|_|   \__|
#################################################
#################################################


############
### DAEMONS
############

exec-once = hypridle
exec-once = systemctl --user start hyprpolkitagent
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = nextcloud --background
exec-once = localsend --hidden
exec-once = swaync

exec-once = ~/.config/vutureland/assets/scripts/float-cascade.sh


########################
### SYSTEMEINSTELLUNGEN
########################

exec-once = hyprctl setcursor $cur_theme $cur_size
exec-once = $desktop_shell


########################
### APPLICATIONS
########################

exec-once = [workspace $start_app1_ws silent] $start_app1
exec-once = [workspace $start_app2_ws silent] $start_app2
exec-once = [workspace $start_app3_ws silent] $start_app3
exec-once = [workspace $start_app4_ws silent] $start_app4
exec-once = [workspace $start_app5_ws silent] $start_app5
exec-once = [workspace $start_app6_ws silent] $start_app6
exec-once = [workspace $start_app7_ws silent] $start_app7
exec-once = [workspace $start_app8_ws silent] $start_app8
exec-once = [workspace $start_app9_ws silent] $start_app9
exec-once = [workspace $start_app10_ws silent] $start_app10
