#######################################
#######################################
##      ___           _               
##     /   \_____   _(_) ___ ___  ___ 
##    / /\ / _ \ \ / / |/ __/ _ \/ __|
##   / /_//  __/\ V /| | (_|  __/\__ \
##  /___,' \___| \_/ |_|\___\___||___/                              
#######################################                                     
#######################################

# See https://wiki.hypr.land/Configuring/Monitors/

input {
  kb_layout = eu
  follow_mouse = 1
  sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
  mouse_refocus = true
  numlock_by_default = true
}

cursor {
  sync_gsettings_theme = true
  no_hardware_cursors = true
  no_warps = true
  default_monitor = $mon1
  zoom_factor = 1
  hide_on_key_press = true
}