#########################
### ENVIRONMENT VARIABLES
#########################

# See https://wiki.hypr.land/Configuring/Environment-variables/

# QT
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

# Toolkit Backend Variables
env = GDK_BACKEND,wayland,x11,*
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

# XDG Specifications
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_MENU_PREFIX,arch-

# For native Wayland apps
env = HYPRCURSOR_THEME,$cur_theme
env = HYPRCURSOR_SIZE,$cur_size

# For X11/Xwayland apps
env = XCURSOR_THEME,$cur_theme
env = XCURSOR_SIZE,$cur_size

env = xx_color_management_v4, 1

xwayland {
  force_zero_scaling = true
}