#########################################################
#########################################################
##    __                                     __         
##   / /   ____ ___  _____  ____________  __/ /__  _____
##  / /   / __ `/ / / / _ \/ ___/ ___/ / / / / _ \/ ___/
## / /___/ /_/ / /_/ /  __/ /  / /  / /_/ / /  __(__  ) 
##/_____/\__,_/\__, /\___/_/  /_/   \__,_/_/\___/____/  
##            /____/    
#########################################################
#########################################################


layerrule{
    name                    = layer_blur
    match:namespace         = (.*)
    blur                    = on
    blur_popups             = on
    ignore_alpha            = 0.1
    animation               = popin 60%
    xray                    = true
}


layerrule{
    name                    = swaync
    $swaync                 = (.*swaync-control-center.*)
    match:namespace         = $swaync
    blur                    = on
    blur_popups             = on
    ignore_alpha            = 0.1
    animation               = slidefade bottom 80%
    xray                    = true
}


layerrule{
    name                    = rofi
    $rofi                   = (.*rofi.*)
    match:namespace         = $rofi
    blur                    = on
    blur_popups             = on
    ignore_alpha            = 0.1
    dim_around              = on
    animation               = slidefade bottom 80%
    xray                    = true
}


layerrule{
    name                    = waybar
    $rofi                   = (.*waybar.*)
    match:namespace         = $waybar
    blur                    = on
    blur_popups             = on
    ignore_alpha            = 0.1
    dim_around              = false
    no_anim                 = true
    xray                    = true
}


layerrule{
    name                    = screenshot
    $screenshot             = (.*hyprpicker.*|.*selection.*)
    match:namespace         = $screenshot
    blur                    = off
    blur_popups             = off 
    ignore_alpha            = 0.1
    no_anim                 = on
    xray                    = true
}

layerrule{
    name                    = noctalia-shell
    $noctalia               = (.*noctalia.*)
    match:namespace         = $noctalia
    blur                    = off
    blur_popups             = off 
    ignore_alpha            = 0.1
    no_anim                 = on
    xray                    = true
}