

decoration:shadow:scale = 0.5

dwindle:force_split = 0
dwindle:preserve_split = 0
dwindle:pseudotile = 1
dwindle:smart_resizing = 1
dwindle:smart_split = 0
dwindle:use_active_for_splits = 0

general:allow_tearing = 1
general:border_size = 2
general:extend_border_grab_area = 20
general:resize_on_border = 1


general {

    gaps_in                 = 8
    gaps_out                = 14
    border_size             = 1
    col.active_border       = $color5
    col.inactive_border     = $background
    extend_border_grab_area = 20
    resize_on_border        = true
    allow_tearing           = true
    layout                  = dwindle

}

decoration {

    rounding  = 5
    dim_modal = true

    blur {

        enabled           = true
        size              = 4
        passes            = 4
        contrast          = 0.5
        noise             = 0.025
        vibrancy          = 0.04
        vibrancy_darkness = 0.08
        xray              = true

    }

    shadow {

        enabled = true
        range = 8
        render_power = 2
        color = $color5

    }

}

misc {

    focus_on_activate   = true
    disable_autoreload  = true

}