##############################################################
##  __  __             _ _
## |  \/  | ___  _ __ (_) |_ ___  _ __ ___
## | |\/| |/ _ \| '_ \| | __/ _ \| '__/ __|
## | |  | | (_) | | | | | || (_) | |  \__ \
## |_|  |_|\___/|_| |_|_|\__\___/|_|  |___/
##############################################################

#<<<SETUP-SECTION-START>>>
$mon1 = DP-2
$mon2 = DP-3

monitorv2 {
  output        = DP-2
  mode          = 2560x1440@165.00
  transform     = 0
  position      = 0x0
  scale         = 1
  bitdepth      = 10
  supports_hdr  = 0
  vrr           = off
  cm            = auto
}

monitorv2 {
  output        = DP-3
  mode          = 1920x1080@200.00
  transform     = 3
  position      = auto
  scale         = 1
  bitdepth      = 10
  supports_hdr  = 0
  vrr           = off
  cm            = auto
}
#<<<SETUP-SECTION-END>>>
