###############################################################
##  ____           _       _
## |  _ \ ___ _ __(_)_ __ | |__   ___ _ __ __ _  _____
## | |_) / _ \ '__| | '_ \| '_ \ / _ \ '__/ _` ||_  / |
## |  __/  __/ |  | | |_) | | | |  __/ | | (_| | / /| |
## |_|   \___|_|  |_| .__/|_| |_|\___|_|  \__,_|/___|_|
##                  |_|
###############################################################

#<<<SETUP-SECTION-START>>>
# Cursor
$cur_theme = breeze_cursors
$cur_size  = 20

# FN Keys
$fn_brightness_up  = F2
$fn_brighness_down = F1
$fn_play_stop_play = F8
$fn_play_next      = F9
$fn_play_prev      = F7
$fn_volume_up      = F12
$fn_volume_down    = F11
$fn_volume_mute    = F10
#<<<SETUP-SECTION-END>>>
