###############################################################
##   ___        _      _
##  / _ \ _   _(_) ___| | __   __ _  ___ ___ ___  ___ ___
## | | | | | | | |/ __| |/ /  / _` |/ __/ __/ _ \/ __/ __|
## | |_| | |_| | | (__|   <  | (_| | (_| (_|  __/\__ \__ \
##  \__\_\\__,_|_|\___|_|\_\  \__,_|\___\___\___||___/___/
###############################################################

#<<<SETUP-SECTION-START>>>
$quick_app1  =
$quick_app2  = librewolf
$quick_app3  =
$quick_app4  =
$quick_app5  =
$quick_app6  =
$quick_app7  =
$quick_app8  =
$quick_app9  = steam
$quick_app10 = steam
#<<<SETUP-SECTION-END>>>
