###############################################################
## _       ___           __                         __
##| |     / (_)___  ____/ /___ _      _________  __/ /__  _____
##| | /| / / / __ \/ __  / __ \ | /| / / ___/ / / / / _ \/ ___/
##| |/ |/ / / / / / /_/ / /_/ / |/ |/ / /  / /_/ / /  __(__  )
##|__/|__/_/_/ /_/\__,_/\____/|__/|__/_/   \__,_/_/\___/____/
###############################################################


focus_on_activate = true


## = = = || Automatical applied rules || = = = ##

windowrule {
    name                    = set_normal
    match:class             = (.*)
    animation               = popin 80%
    opacity                 = 0.9
    xray                    = on
}

windowrule {
    name        = floating_windows
    match:title = $floating_window
    tag         = +floating_app
    float       = true
    center      = true
    size        = 1100 1000
}
windowrule {
    name        = modal_windows
    match:modal = true
    tag         = +floating_app
    float       = true
    center      = true
}
windowrule {
    name        = portal_dialogs
    match:class = (xdg-desktop-portal.*)
    tag         = +floating_app
    float       = true
    center      = true
}
windowrule {
    name        = context_dialogs
    match:title = (.*[Ee]rinnerung.*|.*[Uu]mbenennen.*|.*[Rr]ename.*|.*[Ll]öschen.*|.*[Dd]elete.*|.*[Ee]igenschaften.*|.*[Pp]roperties.*|.*[Bb]estätigen.*|.*[Cc]onfirm.*|.*[Ss]peichern unter.*|.*[Ss]ave [Aa]s.*|.*[Öö]ffnen.*|.*[Oo]pen.*|.*[Ff]ortschritt.*|.*[Pp]rogress.*|.*[Ff]ehler.*|.*[Ee]rror.*|.*[Ww]arnung.*|.*[Ww]arning.*)
    tag         = +floating_app
    float       = true
    center      = true
    size        = 1000
}


## = = = || Opacity rules || = = = ##

windowrule {
    name                = floating
    match:initial_class = $opacity_window
    tag                 = +opacity_window
    opacity             = 1
}
windowrule {
    name                = content_match
    match:content       = (.*video.*|.*game.*)
    tag                 = +opacity_window
    opacity             = 1
}

# STEAM
windowrule {
    name                = steam_opacity
    match:initial_class = (.*[Ss]team.*)
    tag                 = +opacity_window
    opacity             = 1
    center              = true
}
windowrule {
    name        = steam_on_10
    match:title = (.*[Ss]team.*)
    workspace   = 10
}

# SYSTEMMONITORING
windowrule {
    name            = dedicated_system_screen
    match:workspace = 99
    float           = false
    tile            = true
    no_blur         = true
}


## = = = || Manually toggled rules || = = = ##

windowrule {
    name             = no_opacity
    match:tag        = opacity_off
    opacity          = 1
    opaque           = true
    no_blur          = true
}
