###############################################################
##  _    _            _
## | |  | |          | |
## | |  | | ___  _ __| | _____ _ __   __ _  ___ ___  ___
## | |/\| |/ _ \| '__| |/ / __| '_ \ / _` |/ __/ _ \/ __|
## \  /\  / (_) | |  |   <\__ \ |_) | (_| | (_|  __/\__ \
##  \/  \/ \___/|_|  |_|\_\___/ .__/ \__,_|\___\___||___/
##                             | |
##                             |_|
###############################################################

#<<<SETUP-SECTION-START>>>
# $mon1
workspace = 1,  monitor:$mon1, persistent:true, default:true
workspace = 2,  monitor:$mon1, persistent:true
workspace = 3,  monitor:$mon1, persistent:true
workspace = 4,  monitor:$mon1, persistent:true
workspace = 5,  monitor:$mon1, persistent:true

# $mon2
workspace = 6,  monitor:$mon2, persistent:true
workspace = 7,  monitor:$mon2, persistent:true
workspace = 8,  monitor:$mon2, persistent:true
workspace = 9,  monitor:$mon2, persistent:true

# $mon1
workspace = 10,  monitor:$mon1, persistent:false
workspace = 90,  monitor:$mon1, persistent:false
workspace = 99,  monitor:$mon1, persistent:false
workspace = 111,  monitor:$mon1, persistent:false

# $mon2
workspace = 112,  monitor:$mon2, persistent:false

# $mon1
workspace = 1111,  monitor:$mon1, persistent:false
#<<<SETUP-SECTION-END>>>
