-- ═══════════════════════════════════════════════════════
-- Application variables — common across all devices
-- ═══════════════════════════════════════════════════════

-- Scripts live in the read-only package dir (VTL_DIR).
-- Per-user generated state lives in the user dir (VTL_USER_DIR), which
-- welcome_to_velumeron.sh seeds from the package on first run.

clipboard      = "qs -p " .. VTL_DIR .. "/quickshell ipc call clipboard toggle"

-- Launcher, wallpaper switcher, window switcher, clipboard and session menu are now native
-- (quickshell) — the `qs ipc call <target>` overlays replace the old rofi/drun menus.
window_switch  = "qs -p " .. VTL_DIR .. "/quickshell ipc call window open"
-- terminal moved down to the role apps: it is one, and it needs _first_of (defined below).
browser        = browser       or "librewolf"
browser_float  = browser_float or (browser .. " --class=browser-float")
filemanager    = filemanager   or "thunar"
notifications  = VTL_DIR .. "/bin/velumeron --panel-toggle"
-- The picker overlay, not a fixed mode. A KEYBIND STRING and nothing more: it is evaluated when
-- you press the key, never at login, which is why restoring this cannot cost you a session. The two
-- layer rules that came with it stay out — those are the half that touches how the compositor
-- handles surfaces, and one variable at a time.
-- bin/velumeron falls back to the old hyprshot drag if the shell is not up to answer the IPC.
screenshot_cmd = VTL_DIR .. "/bin/velumeron --screenshot"
screen_record  = screen_record or ""
bitwarden      = bitwarden     or "bitwarden"

-- Locks and waits for the lockscreen to finish drawing, THEN suspends (see suspend.sh).
on_sleep       = VTL_DIR .. "/assets/scripts/suspend.sh"
-- Native quickshell lock, engaged straight through its IPC. The session menu's Lock and
-- `velumeron --lock` take the same path, so every MANUAL lock is one call. hypridle keeps the idle
-- and before-sleep locking (loginctl → its lock_cmd → this same IPC), which is where the
-- inhibit_sleep sequencing lives; going through logind for a keypress only adds two processes that
-- have to be alive for the key to do anything.
on_lock        = "qs -p " .. VTL_DIR .. "/quickshell ipc call lock lock"
session_menu   = "qs -p " .. VTL_DIR .. "/quickshell ipc call session toggle"


-- ── Role-based app variables — set per device in user_settings.lua ─────────
-- Fallback: auto-detect the first installed candidate so keybinds work
-- on fresh client installs without needing the GUI "Apply & Reload" step.
local function _first_of(...)
    for _, cmd in ipairs({...}) do
        local h = io.popen("command -v " .. cmd .. " 2>/dev/null")
        if h then
            local r = h:read("*l"); h:close()
            if r and r ~= "" then return cmd end
        end
    end
    return ""
end

-- The terminal is a role app like every other line here, NOT a dependency. It used to be
-- `kitty -c <user dir>/kitty/kitty.conf`, which made one emulator part of the desktop and shipped
-- it a config it never asked for. Theming a terminal is now opt-in per emulator
-- (Settings → Integrations → Terminal) and writes that emulator's OWN config; this only picks
-- which one the keybinds open.
terminal       = terminal      or _first_of("kitty", "foot", "alacritty", "wezterm", "ghostty",
                                            "rio", "konsole", "gnome-terminal", "xterm")
messenger      = messenger     or _first_of("telegram-desktop", "element-desktop", "cinny", "discord", "signal-desktop", "slack")
player         = player        or _first_of("strawberry", "rhythmbox", "lollypop", "clementine", "elisa", "spotify", "audacious", "deadbeef", "musikcube", "vlc")
notes_app      = notes_app     or _first_of("obsidian", "logseq", "joplin", "cherrytree", "zettlr", "rnote")
clock_app      = clock_app     or _first_of("gnome-clocks", "kclock")
mail_app       = mail_app      or _first_of("betterbird", "thunderbird", "evolution", "geary", "neomutt", "aerc")
calendar_app   = calendar_app  or _first_of("gnome-calendar", "korganizer", "calcurse")
tasks_app      = tasks_app     or _first_of("planify", "gnome-todo", "endeavour", "korganizer")
editor_app     = editor_app    or _first_of("neovide", "codium", "code", "zeditor", "kate", "gedit", "mousepad", "featherpad", "gnome-text-editor")

-- ── System-action variables — set per device in user_settings.lua ──────────
wifi_menu      = wifi_menu      or ""
bluetooth_menu = bluetooth_menu or ""
vpn_toggle     = vpn_toggle     or ""
audio_switch   = audio_switch   or ""
mic_mute       = mic_mute       or "pactl set-source-mute @DEFAULT_SOURCE@ toggle"
night_light    = night_light    or ""
dnd_toggle     = dnd_toggle     or ""


-- ── Fallback defaults for device-specific globals ──────────────────────
-- Normally set in user_settings.lua (generated by the setup). On a fresh client
-- without that file these would be nil and the config would error; fall back to
-- sane values so Hyprland always starts. The monitor + workspaces are then
-- auto-configured on first boot (see modules/autostart.lua). user_settings.lua,
-- when present, is loaded before this module, so its values always win.
exec_once_daemons  = exec_once_daemons  or {}
start_apps         = start_apps         or {}
quick_app          = quick_app          or {}
cur_theme          = cur_theme          or "Oxygen"
cur_size           = cur_size           or 24
kb_layout          = kb_layout          or "eu"
