-- ═══════════════════════════════════════════════════════
-- Application variables — common across all devices
-- ═══════════════════════════════════════════════════════

-- Scripts live in the read-only package dir (VTL_DIR).
-- Configs that have to be read alongside wallust-written colour files
-- (kitty.conf, rofi *.rasi) live in the user dir (VTL_USER_DIR), which
-- welcome_to_vutureland.sh seeds from the package on first run.

desktop_shell  = VTL_DIR      .. "/assets/scripts/launch-waybar.sh"
notify_service = "swaync"
clipboard      = VTL_USER_DIR .. "/rofi/assets/clipvault.sh"

launcher       = "rofi -show drun -config "      .. VTL_USER_DIR .. "/rofi/launcher.rasi"
window_switch  = "rofi -show window -config "    .. VTL_USER_DIR .. "/rofi/window-switcher.rasi"
theme_switch   = "rofi -show wallpaper -config " .. VTL_USER_DIR .. "/rofi/wallpaper-switcher.rasi"
terminal       = terminal      or ("kitty -c "   .. VTL_USER_DIR .. "/kitty/kitty.conf")
browser        = browser       or "librewolf"
filemanager    = filemanager   or "thunar"
notifications  = "swaync-client -R -rs -t"
screenshot_cmd = "hyprshot -z --mode region --output-folder ~/Bilder/Screenshots"
screen_record  = screen_record or ""
bitwarden      = bitwarden     or "bitwarden"

on_sleep       = "systemctl suspend"
on_lock        = VTL_DIR      .. "/assets/scripts/launch-hyprlock.sh"
session_menu   = VTL_USER_DIR .. "/rofi/assets/session-menu.sh"


-- ── Role-based app variables — set per device in user_settings.lua ─────────
messenger      = messenger     or ""
player         = player        or ""
notes_app      = notes_app     or ""
clock_app      = clock_app     or ""
mail_app       = mail_app      or ""
calendar_app   = calendar_app  or ""
tasks_app      = tasks_app     or ""
editor_app     = editor_app    or ""

-- ── System-action variables — set per device in user_settings.lua ──────────
wifi_menu      = wifi_menu      or ""
bluetooth_menu = bluetooth_menu or ""
vpn_toggle     = vpn_toggle     or ""
audio_switch   = audio_switch   or ""
mic_mute       = mic_mute       or "pactl set-source-mute @DEFAULT_SOURCE@ toggle"
night_light    = night_light    or ""
dnd_toggle     = dnd_toggle     or "swaync-client --toggle-dnd"


-- ── Fallback defaults for device-specific globals ──────────────────────
-- Normally set in user_settings.lua (generated by the setup). On a fresh client
-- without that file these would be nil and the config would error; fall back to
-- sane values so Hyprland always starts. The monitor + workspaces are then
-- auto-configured on first boot (see modules/autostart.lua). user_settings.lua,
-- when present, is loaded before this module, so its values always win.
exec_once_daemons  = exec_once_daemons  or {}
start_apps         = start_apps         or {}
quick_app          = quick_app          or {}
cur_theme          = cur_theme          or "Oxygen"
cur_size           = cur_size           or 24
kb_layout          = kb_layout          or "eu"
