-- ═══════════════════════════════════════════════════════
-- Application variables — common across all devices
-- ═══════════════════════════════════════════════════════

-- Scripts live in the read-only package dir (VTL_DIR).
-- Configs that have to be read alongside wallust-written colour files
-- (kitty.conf, rofi *.rasi) live in the user dir (VTL_USER_DIR), which
-- welcome_to_velumeron.sh seeds from the package on first run.

desktop_shell  = VTL_DIR      .. "/assets/scripts/launch-shell.sh"
notify_service = "velumeron-notify"
clipboard      = "qs -p " .. VTL_DIR .. "/quickshell ipc call clipboard toggle"

-- Launcher, wallpaper switcher, window switcher, clipboard and session menu are now native
-- (quickshell) — the `qs ipc call <target>` overlays replace the old rofi/drun menus.
window_switch  = "qs -p " .. VTL_DIR .. "/quickshell ipc call window open"
terminal       = terminal      or ("kitty -c "   .. VTL_USER_DIR .. "/kitty/kitty.conf")
browser        = browser       or "librewolf"
browser_float  = browser_float or (browser .. " --class=browser-float")
filemanager    = filemanager   or "thunar"
notifications  = VTL_DIR .. "/bin/velumeron --panel-toggle"
screenshot_cmd = "hyprshot -z --mode region --output-folder ~/Bilder/Screenshots"
screen_record  = screen_record or ""
bitwarden      = bitwarden     or "bitwarden"

on_sleep       = "systemctl suspend"
on_lock        = VTL_DIR      .. "/assets/scripts/launch-hyprlock.sh"
session_menu   = "qs -p " .. VTL_DIR .. "/quickshell ipc call session toggle"


-- ── Role-based app variables — set per device in user_settings.lua ─────────
-- Fallback: auto-detect the first installed candidate so keybinds work
-- on fresh client installs without needing the GUI "Apply & Reload" step.
local function _first_of(...)
    for _, cmd in ipairs({...}) do
        local h = io.popen("command -v " .. cmd .. " 2>/dev/null")
        if h then
            local r = h:read("*l"); h:close()
            if r and r ~= "" then return cmd end
        end
    end
    return ""
end

messenger      = messenger     or _first_of("telegram-desktop", "element-desktop", "cinny", "discord", "signal-desktop", "slack")
player         = player        or _first_of("strawberry", "rhythmbox", "lollypop", "clementine", "elisa", "spotify", "audacious", "deadbeef", "musikcube", "vlc")
notes_app      = notes_app     or _first_of("obsidian", "logseq", "joplin", "cherrytree", "zettlr", "rnote")
clock_app      = clock_app     or _first_of("gnome-clocks", "kclock")
mail_app       = mail_app      or _first_of("betterbird", "thunderbird", "evolution", "geary", "neomutt", "aerc")
calendar_app   = calendar_app  or _first_of("gnome-calendar", "korganizer", "calcurse")
tasks_app      = tasks_app     or _first_of("planify", "gnome-todo", "endeavour", "korganizer")
editor_app     = editor_app    or _first_of("neovide", "codium", "code", "zeditor", "kate", "gedit", "mousepad", "featherpad", "gnome-text-editor")

-- ── System-action variables — set per device in user_settings.lua ──────────
wifi_menu      = wifi_menu      or ""
bluetooth_menu = bluetooth_menu or ""
vpn_toggle     = vpn_toggle     or ""
audio_switch   = audio_switch   or ""
mic_mute       = mic_mute       or "pactl set-source-mute @DEFAULT_SOURCE@ toggle"
night_light    = night_light    or ""
dnd_toggle     = dnd_toggle     or ""


-- ── Fallback defaults for device-specific globals ──────────────────────
-- Normally set in user_settings.lua (generated by the setup). On a fresh client
-- without that file these would be nil and the config would error; fall back to
-- sane values so Hyprland always starts. The monitor + workspaces are then
-- auto-configured on first boot (see modules/autostart.lua). user_settings.lua,
-- when present, is loaded before this module, so its values always win.
exec_once_daemons  = exec_once_daemons  or {}
start_apps         = start_apps         or {}
quick_app          = quick_app          or {}
cur_theme          = cur_theme          or "Oxygen"
cur_size           = cur_size           or 24
kb_layout          = kb_layout          or "eu"
