-- ═══════════════════════════════════════════════════════
-- VELUMERON — Hyprland Lua Configuration
-- https://wiki.hypr.land/Configuring/
-- ═══════════════════════════════════════════════════════

-- Installation paths — set by the entry point (~/.config/hypr/hyprland.lua);
-- fall back to env var or ~/.config/velumeron only if not already provided.
VTL_DIR      = VTL_DIR      or os.getenv("VELUMERON_DIR")      or (os.getenv("HOME") .. "/.config/velumeron")
VTL_USER_DIR = VTL_USER_DIR or os.getenv("VELUMERON_USER_DIR") or (os.getenv("HOME") .. "/.config/velumeron")

-- Colors — wallust writes the live palette to ~/.config/velumeron/hypr.lua/colors.lua.
-- That file is per-machine and never shipped, so on a fresh install neither copy
-- exists and every colour below would be nil. colors.default.lua is the shipped
-- fallback for exactly that gap: first login until the first wallpaper.
local function _try_dofile(path)
    local f = io.open(path, "r")
    if not f then return false end
    f:close()
    dofile(path)
    return true
end
if not _try_dofile(VTL_USER_DIR .. "/hypr.lua/colors.lua") then
    if not _try_dofile(VTL_DIR .. "/hypr.lua/colors.lua") then
        _try_dofile(VTL_DIR .. "/hypr.lua/colors.default.lua")
    end
end

-- Device-specific settings (monitors, workspaces, peripherals)
-- Not in git — generated per device. Always lives in the user dir.
_try_dofile(VTL_USER_DIR .. "/hypr.lua/user_settings.lua")

-- Global window decoration (opacity/blur/vibrancy/xray), set in Settings → Window rules.
-- Generated by apply-decoration.sh; read by look_and_feel + windowrules below. Must load
-- BEFORE look_and_feel. A missing file is a no-op — the shipped defaults stand.
_try_dofile(VTL_USER_DIR .. "/hypr.lua/user_decoration.lua")

-- Modules (order matters: variables before their consumers)
require("modules.gpu")
require("modules.variables")
require("modules.environment")
require("modules.devices")
require("modules.look_and_feel")

-- Active UI style — the design chosen in Settings also themes hyprland.
-- themes/<style>.lua overrides design-specific look on top of look_and_feel (it
-- does NOT touch rounding/border_size, which stay user-controlled). A missing
-- file is a no-op, the look_and_feel default stands. Defaults to "flat".
do
    local theme = "flat"
    local tf = io.open(VTL_USER_DIR .. "/active-theme", "r")
    if tf then
        local line = tf:read("*l"); tf:close()
        if line then line = line:gsub("%s+", ""); if line ~= "" then theme = line end end
    end
    if not _try_dofile(VTL_USER_DIR .. "/hypr.lua/themes/" .. theme .. ".lua") then
        _try_dofile(VTL_DIR .. "/hypr.lua/themes/" .. theme .. ".lua")
    end
end

require("modules.animations")
require("modules.autostart")
require("modules.layouts")
require("modules.windowrules")
require("modules.workspaces")
require("modules.layerrules")
require("modules.keybinds")
require("modules.fancyzones")   -- after keybinds: replaces the MOD+LMB drag bind

-- User-defined tiling layouts (Settings → Layouts) + the persisted layout choice.
-- Generated file — a missing one is a no-op.
_try_dofile(VTL_USER_DIR .. "/hypr.lua/user_layouts.lua")

-- Per-monitor/per-workspace layout assignment + float/endless policies. AFTER
-- user_layouts so custom lua:<name> layouts are registered before rules use
-- them, and after user_settings' workspace rules so its own rules win.
require("modules.layout_manager")



-- ═══════════════════════════════════════════════════════
-- MANUAL OVERRIDES
-- Add device-specific overrides below this line
-- ═══════════════════════════════════════════════════════
 