general {
    lock_cmd                = pidof hyprlock || ~/.config/velumeron/assets/scripts/launch-hyprlock.sh
    before_sleep_cmd        = ~/.config/velumeron/assets/scripts/launch-hyprlock.sh
    after_sleep_cmd         = 
}

listener {
    timeout                 = 360
    on-timeout              = loginctl lock-session
}

listener {
    timeout                 = 840      
    on-timeout              = systemctl suspend
}
