
#<< main monitor >>

background {
    monitor = DP-2
    path = ~/.config/vutureland/assets/wallpaper/hyprlock/glitch-statue.png
    blur_passes = 0
    blur_size = 0
}
label {
    monitor = DP-2
    text = cmd[update:1000] date +"%H:%M"
    font_size = 120
    font_family = Atomic Age
    color = rgb(255, 255, 255)
    halign = left
    valign = bottom
    position = 100, 100
}
input-field {
    monitor = DP-2
    size = 300, 50
    outline_thickness = 0
    outer_color = rgba(255, 255, 255, 0)
    inner_color = rgba(0, 0, 0, 0)
    font_color = rgb(255, 255, 255)
    fade_on_empty = true
    placeholder_text = Password...
    halign = left
    valign = bottom
    position = 150, 40
}

#<< other monitors >>

background {
    monitor = DP-3
    path = ~/.config/vutureland/assets/wallpaper/hyprlock/pure-black.jpg
}
