-- ════════════════════════════════════════════════════════════════════════
--
--  USER SETTINGS — Device-specific settings.
--  Generated by hyprland.sh. Not in git. Do not edit manually.
--
-- ════════════════════════════════════════════════════════════════════════


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  MONITORS
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- <<<MONITORS-START>>>
mon1 = "DP-2"
mon2 = "DP-3"

hl.monitor({
    output       = "DP-2",
    mode         = "2560x1440@165.00",
    transform    = 0,
    position     = "0x0",
    scale        = 1,
    bitdepth     = 10,
    supports_hdr = false,
    vrr          = 0,
    cm           = "auto",
})

hl.monitor({
    output       = "DP-3",
    mode         = "1920x1080@200.00",
    transform    = 3,
    position     = "auto",
    scale        = 1,
    bitdepth     = 10,
    supports_hdr = false,
    vrr          = 0,
    cm           = "auto",
})

--- <<<MONITORS-END>>>


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  WORKSPACES
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- <<<WORKSPACES-START>>>
-- mon1
hl.workspace_rule({ workspace = "1",    monitor = mon1, persistent = true,  default = true })
hl.workspace_rule({ workspace = "2",    monitor = mon1, persistent = true })
hl.workspace_rule({ workspace = "3",    monitor = mon1, persistent = true })
hl.workspace_rule({ workspace = "4",    monitor = mon1, persistent = true })
hl.workspace_rule({ workspace = "5",    monitor = mon1, persistent = true })

-- mon2
hl.workspace_rule({ workspace = "6",    monitor = mon2, persistent = true, layout = "lua:vstack" })
hl.workspace_rule({ workspace = "7",    monitor = mon2, persistent = true, layout = "lua:vstack" })
hl.workspace_rule({ workspace = "8",    monitor = mon2, persistent = true, layout = "lua:vstack" })
hl.workspace_rule({ workspace = "9",    monitor = mon2, persistent = true, layout = "lua:vstack" })

-- Special / utility workspaces
hl.workspace_rule({ workspace = "10",   monitor = mon1, persistent = false })
hl.workspace_rule({ workspace = "90",   monitor = mon1, persistent = false })
hl.workspace_rule({ workspace = "99",   monitor = mon1, persistent = false })
hl.workspace_rule({ workspace = "111",  monitor = mon1, persistent = false })
hl.workspace_rule({ workspace = "112",  monitor = mon2, persistent = false })
hl.workspace_rule({ workspace = "1111", monitor = mon1, persistent = false })
-- <<<WORKSPACES-END>>>


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  PERIPHERALS
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- <<<PERIPHERALS-START>>>
cur_theme = "breeze_cursors"
cur_size  = 20

fn_brightness_up   = "F2"
fn_brightness_down = "F1"
fn_play_stop_play  = "F8"
fn_play_next       = "F9"
fn_play_prev       = "F7"
fn_volume_up       = "F12"
fn_volume_down     = "F11"
fn_volume_mute     = "F10"

-- <<<PERIPHERALS-END>>>


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  QUICK ACCESS APPS  (index = key number)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- <<<QUICKACCESS-START>>>
quick_app = {
    [1]  = "",
    [2]  = "librewolf",
    [3]  = "",
    [4]  = "",
    [5]  = "",
    [6]  = "",
    [7]  = "",
    [8]  = "",
    [9]  = "",
    [10] = "steam",
}
-- <<<QUICKACCESS-END>>>


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  AUTOSTART — Device daemons & workspace startup apps
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- <<<AUTOSTART-START>>>
exec_once_daemons = {
    "openrgb -p ~/.config/OpenRGB/purple-blizzard.orp; sleep 30 && openrgb -p ~/.config/OpenRGB/purple-blizzard.orp",
    "tmux new-session -d -s trcc 'trcc theme-load Custom_drifter'",
    "nextcloud --background",
    "localsend --hidden"
}

-- { app = command, ws = workspace_number }
start_apps = {
}

-- <<<AUTOSTART-END>>>


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  WINDOW RULE VARIABLES
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- <<<WINDOWRULES-START>>>
floating_window = "(.*kitty.*|.*ark.*|.*bitwarden.*)"
opacity_window  = "(.*obsidian.*)"

-- <<<WINDOWRULES-END>>>


hl.window_rule({
    name    = "orca-slicer",
    match   = { class = "(.*Orca.*)" },
    opacity = 1,
    opaque  = true,
    no_blur = true,
})
